// Generated by tools/build-content.js. Edit the JSON source.
module.exports = {
  "seed-1": {
    "duration": 8.8484,
    "cues": [
      {
        "start": 0,
        "end": 1.6825
      },
      {
        "start": 1.6825,
        "end": 3.8849
      },
      {
        "start": 3.8849,
        "end": 6.0466
      },
      {
        "start": 6.0466,
        "end": 8.8484
      }
    ]
  },
  "seed-2": {
    "duration": 10.1758,
    "cues": [
      {
        "start": 0,
        "end": 2.4621
      },
      {
        "start": 2.4621,
        "end": 5.2986
      },
      {
        "start": 5.2986,
        "end": 7.7353
      },
      {
        "start": 7.7353,
        "end": 10.1758
      }
    ]
  },
  "fox-1": {
    "duration": 9.6301,
    "cues": [
      {
        "start": 0,
        "end": 2.6424
      },
      {
        "start": 2.6424,
        "end": 4.9999
      },
      {
        "start": 4.9999,
        "end": 7.3122
      },
      {
        "start": 7.3122,
        "end": 9.6301
      }
    ]
  },
  "fox-2": {
    "duration": 9.7357,
    "cues": [
      {
        "start": 0,
        "end": 2.4881
      },
      {
        "start": 2.4881,
        "end": 4.6002
      },
      {
        "start": 4.6002,
        "end": 7.0673
      },
      {
        "start": 7.0673,
        "end": 9.7357
      }
    ]
  },
  "bear-1": {
    "duration": 9.1629,
    "cues": [
      {
        "start": 0,
        "end": 2.3101
      },
      {
        "start": 2.3101,
        "end": 4.6962
      },
      {
        "start": 4.6962,
        "end": 6.9106
      },
      {
        "start": 6.9106,
        "end": 9.1629
      }
    ]
  },
  "bear-2": {
    "duration": 10.1546,
    "cues": [
      {
        "start": 0,
        "end": 2.5885
      },
      {
        "start": 2.5885,
        "end": 5.1999
      },
      {
        "start": 5.1999,
        "end": 7.3563
      },
      {
        "start": 7.3563,
        "end": 10.1546
      }
    ]
  }
}
