DROP TRIGGER IF EXISTS audit_events_append_only ON audit_events;
DROP FUNCTION IF EXISTS prevent_audit_event_mutation();
DROP TABLE IF EXISTS audit_events;
DROP TABLE IF EXISTS ranking_snapshots;
DROP TABLE IF EXISTS quiz_answers;
DROP TABLE IF EXISTS quiz_attempts;
DROP TABLE IF EXISTS quiz_questions;
DROP TABLE IF EXISTS quiz_packages;
DROP TABLE IF EXISTS content_reviews;
DROP TABLE IF EXISTS content_assets;
DROP TABLE IF EXISTS processing_artifacts;
DROP TABLE IF EXISTS processing_jobs;
DROP TABLE IF EXISTS upload_sessions;
DROP TABLE IF EXISTS ingestion_items;
ALTER TABLE IF EXISTS content_versions DROP CONSTRAINT IF EXISTS content_versions_source_batch_fk;
DROP TABLE IF EXISTS ingestion_batches;
ALTER TABLE IF EXISTS pieces DROP CONSTRAINT IF EXISTS pieces_current_content_version_fk;
DROP TABLE IF EXISTS content_versions;
DROP TABLE IF EXISTS pieces;
DROP TABLE IF EXISTS works;
DROP TABLE IF EXISTS user_profiles;
DROP TABLE IF EXISTS campuses;
DROP TABLE IF EXISTS user_sessions;
DROP TABLE IF EXISTS wechat_identities;
DROP TABLE IF EXISTS users;
DROP FUNCTION IF EXISTS set_updated_at();
