// Generated from catalog.json with npm run content:build. Do not edit by hand.
module.exports = [
  {
    "id": "peter",
    "title": "The Tale of Peter Rabbit",
    "zh": "彼得兔的故事",
    "author": "Beatrix Potter",
    "series": "The World of Peter Rabbit",
    "level": "4.2",
    "words": 952,
    "pages": 56,
    "duration": 322,
    "audioUrl": "https://archive.org/download/peter_rabbit_others_1008_librivox/peterrabbit_01_potter_64kb.mp3",
    "previewAudioUrl": "/audio/peter-rabbit-librivox.mp3",
    "narrator": "Julian Pratley",
    "audioSource": "LibriVox",
    "time": "5 min",
    "category": "fiction",
    "cover": "/assets/peter.png",
    "color": "#d9e4cb",
    "stock": 3,
    "number": "10001",
    "desc": "穿上蓝色外套，跟着好奇的小兔子，悄悄走进麦格先生的花园。一场勇敢又温柔的冒险，从这里开始。"
  },
  {
    "id": "garden",
    "title": "The Secret Garden",
    "zh": "秘密花园",
    "author": "Frances H. Burnett",
    "series": "Classic Stories",
    "level": "4.8",
    "words": 1850,
    "pages": 48,
    "duration": 680,
    "time": "11 min",
    "category": "fiction",
    "cover": "/assets/garden.png",
    "color": "#284e46",
    "stock": 2,
    "number": "10002",
    "desc": "一把旧钥匙、一扇被藤蔓遮住的门，和一个等待春天的花园。和玛丽一起发现成长的力量。"
  },
  {
    "id": "willow",
    "title": "The Wind in the Willows",
    "zh": "柳林风声",
    "author": "Kenneth Grahame",
    "series": "Nature & Friends",
    "level": "4.5",
    "words": 1420,
    "pages": 40,
    "duration": 490,
    "time": "8 min",
    "category": "fiction",
    "cover": "/assets/willow.png",
    "color": "#c5d5e0",
    "stock": 1,
    "number": "10003",
    "desc": "沿着河岸散步，遇见鼹鼠、水鼠和他们的朋友。在四季的风景里，听见友谊的声音。"
  },
  {
    "id": "ocean",
    "title": "A Little Ocean",
    "zh": "小小海洋探索家",
    "author": "Tingyue Demo",
    "series": "Discover Nature",
    "level": "1.8",
    "words": 260,
    "pages": 24,
    "duration": 180,
    "time": "3 min",
    "category": "nonfiction",
    "cover": "/assets/ocean.png",
    "color": "#447e9b",
    "stock": 0,
    "number": "10004",
    "desc": "海浪下面住着谁？认识海洋里的小伙伴，开启一次蓝色的自然探索。"
  },
  {
    "id": "fox",
    "title": "The Fox and the Grapes",
    "zh": "狐狸与葡萄",
    "author": "Aesop",
    "series": "Aesop's Fables",
    "level": "2.1",
    "words": 320,
    "pages": 20,
    "duration": 240,
    "time": "4 min",
    "category": "fiction",
    "cover": "/assets/fox.png",
    "color": "#cc7654",
    "stock": 4,
    "number": "10005",
    "desc": "高高的葡萄架下，一只狐狸想到了什么？在一个小故事里，找到值得思考的大道理。"
  },
  {
    "id": "stars",
    "title": "Under the Stars",
    "zh": "星空下的秘密",
    "author": "Tingyue Demo",
    "series": "Discover Nature",
    "level": "2.0",
    "words": 380,
    "pages": 28,
    "duration": 280,
    "time": "5 min",
    "category": "nonfiction",
    "cover": "/assets/stars.png",
    "color": "#303c5d",
    "stock": 2,
    "number": "10006",
    "desc": "夜幕降临，抬头看一看。和我们一起认识月亮、星星与遥远的银河。"
  }
]
