const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs')
const baseUrl=process.env.TINGYUE_PREVIEW_URL||'http://127.0.0.1:4173'
let browser
;(async()=>{
 fs.mkdirSync('artifacts/production',{recursive:true})
 const response=await fetch(baseUrl+'/audio/peter-rabbit-librivox.mp3',{headers:{Range:'bytes=0-1023'}})
 assert.equal(response.status,206);assert.equal((await response.arrayBuffer()).byteLength,1024)
 assert.equal(response.headers.get('content-type'),'audio/mpeg')
 browser=await chromium.launch({headless:true,channel:'msedge'})
 const page=await browser.newPage({viewport:{width:390,height:844}})
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto(baseUrl+'/#player?id=peter-rabbit');await page.locator('.play-button').click()
 await page.waitForFunction(()=>window.previewAudio && !previewAudio.paused && previewAudio.currentTime>1,{},{timeout:20000})
 await page.evaluate(async()=>{window.audioTestContext=new AudioContext();const source=audioTestContext.createMediaElementSource(previewAudio);window.audioTestAnalyser=audioTestContext.createAnalyser();source.connect(audioTestAnalyser);audioTestAnalyser.connect(audioTestContext.destination);await audioTestContext.resume()})
 await page.waitForFunction(()=>{const bins=new Float32Array(audioTestAnalyser.fftSize);audioTestAnalyser.getFloatTimeDomainData(bins);return bins.some(x=>Math.abs(x)>.001)},{},{timeout:10000})
 const metadata=await page.evaluate(()=>({duration:previewAudio.duration,src:previewAudio.currentSrc,decodedSamples:true}))
 assert.ok(metadata.duration>320 && metadata.duration<325)
 await page.locator('.play-button').click();const paused=await page.evaluate(()=>previewAudio.currentTime);await page.waitForTimeout(400);assert.ok(Math.abs(await page.evaluate(()=>previewAudio.currentTime)-paused)<.1)
 await page.locator('.play-button').click();await page.waitForFunction(t=>previewAudio.currentTime>t+.3,paused);assert.ok(await page.evaluate(()=>previewAudio.currentTime)>paused)
 await page.locator('input[type=range]').evaluate(el=>{el.value='120';el.dispatchEvent(new Event('change',{bubbles:true}))})
 await page.waitForFunction(()=>previewAudio.currentTime>=120 && previewAudio.currentTime<124)
 await page.locator('[data-action="speed"]').click();assert.equal(await page.evaluate(()=>previewAudio.playbackRate),1.25)
 const trustStart=await page.evaluate(()=>previewAudio.currentTime)
 await page.waitForFunction(start=>previewAudio.currentTime>start+6.5,trustStart)
 await page.locator('.play-button').click()
 const trustedCheckpoint=await page.evaluate(()=>JSON.parse(localStorage.getItem('tingyue.product.v1')).progress['peter-rabbit-01'].checkpointSeconds)
 assert.ok(trustedCheckpoint>trustStart+5)
 await page.locator('.play-button').click();await page.waitForFunction(checkpoint=>previewAudio.currentTime>checkpoint+.2,trustedCheckpoint)
 // Leaving the player keeps the global session alive; the hidden page must stop receiving updates.
 const beforeLeave=await page.evaluate(()=>{window.detachedPlayerPage=window.currentPage;return {audio:previewAudio.currentTime,page:currentPage.data.position}})
 await page.evaluate(()=>{location.hash='home'})
 await page.waitForFunction(()=>location.hash==='#home'&&window.currentPage.data.route==='home')
 await page.waitForTimeout(600)
 const away=await page.evaluate(()=>({audio:previewAudio.currentTime,detached:detachedPlayerPage.data.position}))
 assert.ok(away.audio>beforeLeave.audio+.3)
 assert.equal(away.detached,beforeLeave.page)
 await page.evaluate(()=>{location.hash='player?id=peter-rabbit'})
 await page.waitForFunction(()=>location.hash.includes('player')&&window.currentPage.data.route==='player'&&currentPage.data.playing)
 const rejoined=await page.evaluate(()=>({pieceId:currentPage.data.book.pieceId,position:currentPage.data.position,rate:currentPage.data.rate,audio:previewAudio.currentTime}))
 assert.equal(rejoined.pieceId,'peter-rabbit-01');assert.equal(rejoined.rate,1.25);assert.ok(Math.abs(rejoined.position-rejoined.audio)<1)
 // A user pause remains paused while browsing elsewhere and after returning.
 await page.locator('.play-button').click()
 const userPaused=await page.evaluate(()=>previewAudio.currentTime)
 await page.evaluate(()=>{location.hash='recent'});await page.waitForFunction(()=>window.currentPage.data.route==='recent');await page.waitForTimeout(400)
 assert.ok(Math.abs(await page.evaluate(()=>previewAudio.currentTime)-userPaused)<.1)
 await page.evaluate(()=>{location.hash='player?id=peter-rabbit'})
 await page.waitForFunction(()=>window.currentPage.data.route==='player'&&!currentPage.data.playing)
 assert.ok(Math.abs(await page.evaluate(()=>currentPage.data.position)-userPaused)<1)
 await page.locator('.play-button').click();await page.waitForFunction(t=>previewAudio.currentTime>t+.2,userPaused)
 await page.screenshot({path:'artifacts/production/real-audio-playing.png'})
 const checkpointBeforeTail=await page.evaluate(()=>JSON.parse(localStorage.getItem('tingyue.product.v1')).progress['peter-rabbit-01'].checkpointSeconds)
 await page.evaluate(()=>{previewAudio.currentTime=previewAudio.duration-.3});await page.waitForFunction(()=>previewAudio.ended)
 const tailProgress=await page.evaluate(()=>JSON.parse(localStorage.getItem('tingyue.product.v1')).progress['peter-rabbit-01'])
 assert.equal(tailProgress.completed,false);assert.equal(tailProgress.checkpointSeconds,checkpointBeforeTail)
 // A full browser reload represents a new JS process: restore paused at the trusted checkpoint.
 await page.reload();await page.waitForFunction(()=>window.currentPage&&currentPage.data.route==='player')
 const restart=await page.evaluate(()=>({position:currentPage.data.position,playing:currentPage.data.playing,hasAudio:!!window.previewAudio}))
 assert.equal(restart.playing,false);assert.ok(Math.abs(restart.position-checkpointBeforeTail)<1,JSON.stringify({restart,checkpointBeforeTail,tailProgress}));assert.equal(restart.hasAudio,false)
 await page.locator('.play-button').click();await page.waitForFunction(checkpoint=>window.previewAudio&&previewAudio.currentTime>checkpoint+.2,checkpointBeforeTail,{timeout:20000})
 // Production contains Peter Rabbit only, so next track must not escape to Demo books.
 await page.evaluate(()=>window.currentPage.nextTrack({currentTarget:{dataset:{step:1}}}));assert.equal(await page.evaluate(()=>window.currentPage.data.book.id),'peter-rabbit')
 assert.deepEqual(errors,[])
 const result={...metadata,bytes:2580786,range:'PASS',play:'PASS',pauseResume:'PASS',seek:'PASS',rate:'PASS',crossPageSession:'PASS',userPauseGuard:'PASS',lifecycleCleanup:'PASS',tailSeekCompletionGuard:'PASS',restartCheckpoint:'PASS',productionCatalogGuard:'PASS',errors}
 fs.writeFileSync('artifacts/production/audio-test.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result))
 await browser.close()
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1})
