const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs')
let browser
;(async()=>{
 fs.mkdirSync('artifacts/production',{recursive:true})
 const response=await fetch('http://127.0.0.1:4173/audio/peter-rabbit-librivox.mp3',{headers:{Range:'bytes=0-1023'}})
 assert.equal(response.status,206);assert.equal((await response.arrayBuffer()).byteLength,1024)
 assert.equal(response.headers.get('content-type'),'audio/mpeg')
 browser=await chromium.launch({headless:true,channel:'msedge'})
 const page=await browser.newPage({viewport:{width:390,height:844}})
 const errors=[];page.on('pageerror',e=>errors.push(e.message))
 await page.goto('http://127.0.0.1:4173/#player?id=peter');await page.locator('.play-button').click()
 await page.waitForFunction(()=>window.previewAudio && !previewAudio.paused && previewAudio.currentTime>1,{},{timeout:20000})
 await page.evaluate(async()=>{window.audioTestContext=new AudioContext();const source=audioTestContext.createMediaElementSource(previewAudio);window.audioTestAnalyser=audioTestContext.createAnalyser();source.connect(audioTestAnalyser);audioTestAnalyser.connect(audioTestContext.destination);await audioTestContext.resume()})
 await page.waitForFunction(()=>{const bins=new Float32Array(audioTestAnalyser.fftSize);audioTestAnalyser.getFloatTimeDomainData(bins);return bins.some(x=>Math.abs(x)>.001)},{},{timeout:10000})
 const metadata=await page.evaluate(()=>({duration:previewAudio.duration,src:previewAudio.currentSrc,decodedSamples:true}))
 assert.ok(metadata.duration>320 && metadata.duration<325)
 await page.locator('.play-button').click();const paused=await page.evaluate(()=>previewAudio.currentTime);await page.waitForTimeout(400);assert.ok(Math.abs(await page.evaluate(()=>previewAudio.currentTime)-paused)<.1)
 await page.locator('.play-button').click();await page.waitForFunction(t=>previewAudio.currentTime>t+.3,paused);assert.ok(await page.evaluate(()=>previewAudio.currentTime)>paused)
 await page.locator('input[type=range]').evaluate(el=>{el.value='120';el.dispatchEvent(new Event('change',{bubbles:true}))})
 await page.waitForFunction(()=>previewAudio.currentTime>=120 && previewAudio.currentTime<124)
 await page.locator('[data-action="speed"]').click();assert.equal(await page.evaluate(()=>previewAudio.playbackRate),1.25)
 await page.screenshot({path:'artifacts/production/real-audio-playing.png'})
 await page.evaluate(()=>{previewAudio.currentTime=previewAudio.duration-.3});await page.waitForFunction(()=>previewAudio.ended)
 assert.equal(await page.evaluate(()=>JSON.parse(localStorage.getItem('tingyue.product.v1')).progress.peter.completed),true)
 // Production contains Peter Rabbit only, so next track must not escape to Demo books.
 await page.evaluate(()=>window.currentPage.nextTrack({currentTarget:{dataset:{step:1}}}));assert.equal(await page.evaluate(()=>window.currentPage.data.book.id),'peter')
 assert.deepEqual(errors,[])
 const result={...metadata,bytes:2580786,range:'PASS',play:'PASS',pauseResume:'PASS',seek:'PASS',rate:'PASS',ended:'PASS',productionCatalogGuard:'PASS',errors}
 fs.writeFileSync('artifacts/production/audio-test.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result))
 await browser.close()
})().catch(async e=>{console.error(e);if(browser)await browser.close();process.exitCode=1})
