const fs = require('fs')
const path = require('path')
const dir = path.join(__dirname, '../modules/listen-read/content')
for (const name of ['stories', 'timings', 'dictionary']) {
  const data = JSON.parse(fs.readFileSync(path.join(dir, name + '.json'), 'utf8'))
  fs.writeFileSync(path.join(dir, name + '.js'), '// Generated by tools/build-content.js. Edit the JSON source.\nmodule.exports = ' + JSON.stringify(data, null, 2) + '\n')
}
console.log('Built native mini-program content modules.')
