const { chromium } = require('playwright')
const fs=require('node:fs')
;(async()=>{
 fs.mkdirSync('artifacts',{recursive:true})
 const browser=await chromium.launch({headless:true,channel:'msedge'})
 const page=await browser.newPage({viewport:{width:1440,height:1100},deviceScaleFactor:1})
 const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())})
 await page.goto('http://127.0.0.1:4173');await page.waitForSelector('.home-book');await page.screenshot({path:'artifacts/home-desktop.png',fullPage:true})
 console.log(JSON.stringify({title:await page.title(),errors,images:await page.locator('#app img').evaluateAll(els=>els.filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src))}))
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:'artifacts/home-mobile.png',fullPage:true})
 await page.locator('#device').evaluate(el=>el.scrollTop=510);await page.screenshot({path:'artifacts/book-list-mobile.png'});await page.locator('#device').evaluate(el=>el.scrollTop=0)
 await page.goto('http://127.0.0.1:4173/#detail');await page.waitForSelector('.detail-cover');await page.screenshot({path:'artifacts/detail-mobile.png',fullPage:true})
 await page.goto('http://127.0.0.1:4173/#player');await page.waitForSelector('.player-cover');await page.screenshot({path:'artifacts/player-mobile.png',fullPage:true})
 await browser.close()
})().catch(e=>{console.error(e);process.exitCode=1})
